name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt update
        sudo apt install -y build-essential gcc g++ make

    - name: Install dependencies
      if: matrix.os == 'windows-latest'
      run: |
        choco install make
        choco install mingw

    - name: Install dependencies
      if: matrix.os == 'macos-latest'
      run: |
        brew update
        brew install gcc make

    - name: Build
      run: |
        make

    - name: Run checks
      run: |
        make run

    - name: Install
      run: |
        make install

    - name: Run tests
      run: |
        make test
