name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo chmod 777 ./configure && ./configure

    - name: Install dependencies
      run: make

    - name: Run check
      run: make run

    - name: Run install
      run: make install
